# Generated by Django 3.2.16 on 2023-11-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('booking_date', models.DateField(null=True)),
                ('flight_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('flight_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('departure_airport', models.CharField(max_length=100)),
                ('arrival_airport', models.CharField(max_length=10)),
                ('airline', models.CharField(max_length=100)),
                ('flight_class', models.CharField(max_length=10)),
                ('flight_no', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('departure_date', models.DateField(null=True)),
                ('arrival_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'flight_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('booking_id', models.IntegerField()),
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'payment_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'register',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('seat_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('flight_id', models.CharField(max_length=10)),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_class', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
