# Generated by Django 3.2.16 on 2023-11-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('booking_date', models.DateField()),
                ('flight_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'booking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('booking_id', models.IntegerField()),
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'payment_method',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'register',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('flight_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('seat_class', models.CharField(max_length=100)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('departure_date', models.DateField()),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ticket',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('seat_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('flight_id', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=100)),
                ('seat_class', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seat',
                'managed': True,
                'unique_together': {('flight_id', 'seat_class')},
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id_no', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('ticket_id', models.OneToOneField(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, to='index.ticket')),
            ],
            options={
                'db_table': 'passenger',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_airport', models.CharField(max_length=100)),
                ('arrival_airport', models.CharField(max_length=100)),
                ('airline', models.CharField(max_length=100)),
                ('flight_class', models.CharField(max_length=100)),
                ('flight_no', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=200)),
                ('flight_id', models.ForeignKey(db_column='flight_id', on_delete=django.db.models.deletion.CASCADE, to='index.seat')),
            ],
            options={
                'db_table': 'flight',
                'managed': True,
            },
        ),
    ]
