# Generated by Django 3.2.16 on 2023-11-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('flight_id', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=100)),
                ('seat_class', models.CharField(max_length=10)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('departure_date', models.DateField()),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={},
        ),
    ]
